apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: paymybuddy
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      name: storage-pv
