apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: pmb-app
  name: pmb-app
  namespace: paymybuddy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    group: app
  type: NodePort
